apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "go-react.fullname" . }}-app-ingress
  labels:
  {{- include "go-react.labels" . | nindent 4 }}
spec:
  rules:
  - host: go-react-app.lab
    http:
      paths:
      - backend:
          service:
            name: '{{ include "go-react.fullname" . }}-frontend-app-service'
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "go-react.fullname" . }}-backend-app-service'
            port:
              number: 8080
        path: /api
        pathType: Prefix