apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-react.fullname" . }}-app-config
  labels:
  {{- include "go-react.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.appConfig.dbHost | quote }}