apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-react.fullname" . }}-backend-app-service
  labels:
  {{- include "go-react.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendAppService.type }}
  selector:
    app: backend-app
  {{- include "go-react.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backendAppService.ports | toYaml | nindent 2 -}}