apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "go-react.fullname" . }}-local-path
  labels:
  {{- include "go-react.labels" . | nindent 4 }}
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer