apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "go-react.fullname" . }}-postgres-pvc
  labels:
  {{- include "go-react.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.postgresPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresPvc.storageClass | quote }}