apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-react.fullname" . }}-postgres-secret
  labels:
  {{- include "go-react.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: {{ required "postgresSecret.postgresDb is required" .Values.postgresSecret.postgresDb
    | quote }}
  POSTGRES_PASSWORD: {{ required "postgresSecret.postgresPassword is required" .Values.postgresSecret.postgresPassword
    | quote }}
  POSTGRES_USER: {{ required "postgresSecret.postgresUser is required" .Values.postgresSecret.postgresUser
    | quote }}
type: Opaque