apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "go-react.fullname" . }}-postgres-pv
  labels:
  {{- include "go-react.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: {{ .Values.pv.size }}
  hostPath:
    path: {{ .Values.pv.hostpath.path }}
  storageClassName: local-path